Update Go base image to version 1.25-alpine
1.24 gives the following error:

 => ERROR [builder 5/6] RUN go mod download                                                                                                                                            0.6s
------                                                                                                                                                                                      
 > [builder 5/6] RUN go mod download:
0.428 go: go.mod requires go >= 1.25.0 (running go 1.24.13; GOTOOLCHAIN=local)
------
Dockerfile:7
--------------------
   5 |     WORKDIR /app
   6 |     COPY . /app
   7 | >>> RUN go mod download
   8 |     RUN go build ./cmd/dnsx
   9 |     
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1