ci: fix build
`set-env` is deprecated

```
Error: Unable to process command '::set-env name=GOROOT::/opt/hostedtoolcache/go/1.15.6/x64' successfully.
```